<div id="header">
    <img id="logo" src="../images/logo.png" alt="">
    <div id="search">
        <form action="../search_result.php" method="post">
            <input type="radio" name="newstype" value="title" checked="true">按标题
            <input type="radio" name="newstype" value="content">按内容
            <input type="text" name="searchfield">
            <input type="submit" value="搜索新闻">
            <a href="../admin_login.php">后台管理中心</a>
        </form>
    </div>
</div>


